### ISSUE TITLE
Show

### ISSUE THREAD

**Issue by lucassgomes** [JnCM/TP_03_AEDS---JOSUE_3465---LUCAS_3511---MATEUS_3488#1]
Achei seu código bacana, chefe! Consegui saber o q fazer aqui no meu depois de ler o seu kkkk Bem documentado. Show! 
OBS: Não dei CTRL+C CTRL+V kkk

**Comment by JnCM** [comment]
Kkkk Tranquilo cara, estamos aí pra isso, precisando de qualquer coisa, só chamar!
